version: "3.9"

volumes:
  minty_postgres:
    external: false

services:
  db:
    image: postgres
    hostname: minty-db
    volumes:
      - minty_postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: minty
      POSTGRES_USER: atwood
      POSTGRES_PASSWORD: password
  api:
    hostname: minty-api
    build: 
      context: ./api
      dockerfile: Dockerfile
    # Inject command to be executed by entrypoint
    command: /bin/bash -c "python3 -m flask run --host=0.0.0.0"
    volumes:
      - ./api:/app/api
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - ./api/.env